print('Welcome to the tip calculator!')
bill = float(input('What was the total bill?\n$ '))
tip = float(input('How much tip would you like to give? 10, 12, or 15?\n'))
split = int(input('How many people to split the bill?\n'))
result = (bill * ((tip / 100) + 1) / (split))
print(f'Each person shoul pay: ${result}')